CREATE TABLE Minions
(
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Age SMALLINT,
	PRIMARY KEY (id)
);

CREATE TABLE Towns
(
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Age SMALLINT,
	PRIMARY KEY (Id)
);